monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
    handlers:
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            channels: ["!event"]
            max_files: 10
        deprecation:
            type: rotating_file
            channels: [ deprecation ]
            path: "%kernel.logs_dir%/%kernel.environment%.deprecation.log"
            max_files: 10
